stages:
  - build

variables:
  DOCKER_REPOSITORY: hs110influx
  DOCKER_TAG: latest
  DOCKER_REGISTRY: docker.jfrog.wouterstemgee.be
  
docker_build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci -p gitlab-ci ${DOCKER_REGISTRY}
  script:
    - export DOCKER_HOST=tcp://localhost:2375
    - docker build --pull --rm -f "Dockerfile" -t ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:${DOCKER_TAG} "."
    - docker push ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:${DOCKER_TAG}
  only:
    - master

docker_run:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - export DOCKER_HOST=tcp://localhost:2375
    - docker run --rm -it ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:${DOCKER_TAG}
