stages:
  - build

docker_build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
  - export CI_REGISTRY="registry.wouterstemgee.be"
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker info
  script:
    - docker build --pull --rm -f "Dockerfile" -t hs110influx:latest "."
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

docker_run:
  stage: build
  script:
    - docker run --rm -it  hs110influx:latest
