stages:
  - build

docker_build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u gitlab-ci -p gitlab-ci docker.jfrog.wouterstemgee.be
    - docker info
  script:
    - docker build --pull --rm -f "Dockerfile" -t hs110influx:latest "."
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

docker_run:
  stage: build
  script:
    - docker run --rm -it  hs110influx:latest
