stages:
  - build

variables:
  - PROJECT_NAME=hs110influx
  - DOCKER_REGISTRY=docker.jfrog.wouterstemgee.be
docker_build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci -p gitlab-ci $DOCKER_REGISTRY
  script:
    - docker build --pull --rm -f "Dockerfile" -t $PROJECT_NAME "."
    - docker tag $PROJECT_NAME $DOCKER_REGISTRY/$PROJECT_NAME:latest
    - docker push $DOCKER_REGISTRY/$PROJECT_NAME:latest
  only:
    - master

docker_run:
  stage: build
  script:
    - docker run --rm -it $PROJECT_NAME:latest
